### ISSUE TITLE
Music stops after 1 second using wireless connections

### ISSUE THREAD

**Issue by bigshant** [terreng/computercraft-streaming-music#2]
Hey, I'm trying to use this in conjunction with https://github.com/jdf221/CC-WirelessPeripheral?tab=readme-ov-file#usage. 

I'm using All of Fabric 7

For some reason it works for only 1 second, but then it stops playing right after. I modified the code to use wpp.peripherals.find() instead of peripherals.find(). 

Modified section:
![image](https://github.com/user-attachments/assets/b1e013c2-fd24-4bac-a64d-bd9e07c4995f)

Looking to find answers for why the music stops working when using this addition, but it works otherwise.

I have two speakers that are directly connected to the computer, with one additional computer with a speaker wirelessly connected via a modem.

![image](https://github.com/user-attachments/assets/59f1d382-73dc-4f92-8192-991f419e649a)

![image](https://github.com/user-attachments/assets/57f83974-f1d2-4d01-aaa2-798f296a4ecc)

**Comment by terreng** [comment]
Sorry, I don't know the answer because I've never used that before. If it works fine out the box, but then breaks when you use that addition, then it sounds like a problem with that addition. I would suggest asking over there instead.

**Comment by bigshant** [comment]
Okay, thank you!
