### ISSUE TITLE
search works, but music doesn't play

### ISSUE THREAD

**Issue by andyqng** [terreng/computercraft-streaming-music#6]
i'm able to search for music and press play on them, but when i press play it immediately stops and no music starts playing. what can i do to fix this?

https://github.com/user-attachments/assets/3d8dac63-8be6-4af4-9947-c8cd272d0716

**Comment by terreng** [comment]
Yeah sorry the unofficial API I was using to download videos from YouTube stopped working. I can fix it on the back end when I get the chance.

**Comment by Skript92** [comment]
Any updates on this? You could use cobalt.tools to download the videos from YouTube but I have no idea of how to change the code to make that work

**Comment by terreng** [comment]
> Any updates on this? You could use cobalt.tools to download the videos from YouTube but I have no idea of how to change the code to make that work

The code does currently use cobalt.tools but they recently shut down their API, which is why it stopped working.

**Comment by terreng** [comment]
This is fixed for now. I switched to a different cobalt instance. But it will likely break again in the future.
